# docker-compose.yml

version: "3.7"
services:
    mongo:
        image: mongo
        ports:
          - '27017:27017'
        environment:
          - ALLOW_EMPTY_PASSWORD=yes

    backend:
        build:
            context: .
        depends_on:
            - mongo
        ports:
            - '8000:8000'
